### ISSUE TITLE
Can't boot with Pentium

### ISSUE THREAD

**Issue by shibadogcap** [CoolestEnoch/surface-go3-opencore#2]
https://github.com/CoolestEnoch/surface-go3-opencore/assets/132909895/d4bc83a9-d53e-4be5-9b9a-a5407869358b

I tried to boot the Sonoma on a Pentium-equipped Surface Go 3, but the screen display became distorted and it kept rebooting. I tried switching the SIP and resetting the NVRAM, but nothing seemed to work. If you have time, please let me know what to do.

**Comment by CoolestEnoch** [comment]
May I have your MacOS version..? it is 14.0 or 14.4 above? I mean, the installation image's version. BTW, you can boot into the installation interface but not able to boot into system? So strange.... Or, try to disable the `AirportItlwm` kext then retry?

Or maybe that's the difference between CN model and JP model.... I got feedback from users in CN with Pentium that this is able to boot for them...

**Comment by shibadogcap** [comment]
I got installer from Mac App Store, version is 14.5.(I couldn't get 14.0 or 14.3.1 installer...)
When I delete AirportItlwm_Sonoma.kext, I could boot and start installing. Thank you very much!!

**Comment by shibadogcap** [comment]
I turn on AirPortItIwm but Wi-Fi doesn't work and this is result of uname -a

Darwin SurfacenoMacBook-Air.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May 1 20:09:52PDT 2024; root:xnu-10063.121.3-5/RELEASE_X86_64 x86_64![IMG_20240703_064806889.jpg](https://github.com/CoolestEnoch/surface-go3-opencore/assets/132909895/dda29461-3c0b-405a-ad76-9a83c0dd1f3a)

**Comment by CoolestEnoch** [comment]
Ah, I got it. Wait me some hours to fix it, I'm now on subway 😂

**Comment by CoolestEnoch** [comment]
Done, check for [releases](https://github.com/CoolestEnoch/surface-go3-opencore/releases/tag/opencore099v3) and have a try. Feel free to give a feedback ; )

**Comment by shibadogcap** [comment]
Now I can use Wi-Fi in Mac OS recovery!!!
I'm installing 14.5. Very good job!! I really appreciate it!

**Comment by CoolestEnoch** [comment]
If your surface's temperature gets so high and meet the threshold, the speed of CPU will be limited at 0.39 GHz (for core i3 device) and it will be soooooooooo slow for use. That's the firmware limit from Microsoft and can be reproduced in both Windows, ChromeOS and Arch Linux. What I did was to disable `Intel Turbo Boost`, in that case the device's temperature won't be higher than 70 Celsius (at 40 degrees north latitude). I use the software named `Turbo Boost Switcher` to do that in MacOS and `Throttle Stop` in Windows. For ChromeOS and other Linux distro, just `echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo` in terminal. Hope this could help.

**Comment by zampemo** [comment]
@CoolestEnoch Hi mate, thanks a lot for your time and dedication to bring MacOS to the Surface Go 3. It's brilliant! Out of curiosity, given how slow this device is with basically any Windows version, I've installed it on my Pentium Gold 6500Y Go 3 (with 8GB RAM + 128GB SSD) and it works wonderfully overall I'd say.

I've been able to install Sonoma directly from Recovery and then everything basically worked OOB.
I'm still getting issues trying to activate iMessage/FaceTime (already changed MLB, etc.) but I don't care much atm. I would prefer if we were able to get the battery recognized (I read it's complicated as a specific kext probably needs to be written) and a device a lil bit more cold while using it (I'll try Turbo Boost Switcher as you said).
Touchscreen isn't working but keyboard + touchpad (with every gestures) works wonderfully so I won't complain at all. Even sleep when the keyboard lid is closed seems to be working fine as well as resume which is instant.
Also headphones plugged into the jack are working but the mic isn't recognized (the Go 3 one works fine). BT headphones works also with mic so that's a workaround.

Overall I'm satisfied, hopefully we can tweak it more to make it even better :)

Note: I used/configured OpenCore in the past for my desktop so I used your package and modified it with the latest v1.0.1 (even though I didn't search for differences in the config.plist, will do that later on or with the next version).
Also I didn't make any adjustment for the slightly different processor (vs your Core i3) and Integrated Graphics (which is an Intel Graphics 615 if I remember correctly) --> should I change some values when we talk about graphics? It seems to be already correctly recognized by the System so I'd leave it as it is.

![Screenshot 2024-08-18 alle 10 34 59](https://github.com/user-attachments/assets/61ec05c0-c7bd-4282-8686-5ddac3df7ac2)
![Screenshot 2024-08-18 alle 10 36 39](https://github.com/user-attachments/assets/36538d4a-afc5-4213-8be5-415ea2f7f2a3)

**Comment by CoolestEnoch** [comment]
> @CoolestEnoch Hi mate, thanks a lot for your time and dedication to bring MacOS to the Surface Go 3. It's brilliant! Out of curiosity, given how slow this device is with basically any Windows version, I've installed it on my Pentium Gold 6500Y Go 3 (with 8GB RAM + 128GB SSD) and it works wonderfully overall I'd say.
> 
> I've been able to install Sonoma directly from Recovery and then everything basically worked OOB.
> I'm still getting issues trying to activate iMessage/FaceTime (already changed MLB, etc.) but I don't care much atm. I would prefer if we were able to get the battery recognized (I read it's complicated as a specific kext probably needs to be written) and a device a lil bit more cold while using it (I'll try Turbo Boost Switcher as you said).
> Touchscreen isn't working but keyboard + touchpad (with every gestures) works wonderfully so I won't complain at all. Even sleep when the keyboard lid is closed seems to be working fine as well as resume which is instant.
> Also headphones plugged into the jack are working but the mic isn't recognized (the Go 3 one works fine). BT headphones works also with mic so that's a workaround.
> 
> Overall I'm satisfied, hopefully we can tweak it more to make it even better :)
> 
> Note: I used/configured OpenCore in the past for my desktop so I used your package and modified it with the latest v1.0.1 (even though I didn't search for differences in the config.plist, will do that later on or with the next version).
> Also I didn't make any adjustment for the slightly different processor (vs your Core i3) and Integrated Graphics (which is an Intel Graphics 615 if I remember correctly) --> should I change some values when we talk about graphics? It seems to be already correctly recognized by the System so I'd leave it as it is.
> 
> ![Screenshot 2024-08-18 alle 10 34 59](https://github.com/user-attachments/assets/61ec05c0-c7bd-4282-8686-5ddac3df7ac2)
> ![Screenshot 2024-08-18 alle 10 36 39](https://github.com/user-attachments/assets/36538d4a-afc5-4213-8be5-415ea2f7f2a3)
> 



It's great to get your feedback and to know that you found my project appealing! ;)
Of course you can, and just feel free to open a pull request 😉 I'm busy in the last half of this year so I don't have enough time to catch up with the latest version of OpenCore...feel sorry about that😂
For the question about Pentium and i3 edition of Surface you mentioned, I'd like to say that this repository is based on [this project](https://github.com/djmanri3/OpenCoreBigSur_Microsoft_Surface_Go_3), for the original project has suspended updating and only support MacOS Big Sur till now. And you can see the conversations above here in this issue, it works on Pentium edition Surface go 3.
For problems about Facetime and iMessage, I'm sorry that I can't test these stuffs because I don't have any other apple devices😂
For problems about battery status, I've tried with any other SMC kexts, it doesn't work. However I found that there is only [BigSurface project](https://github.com/Xiashangning/BigSurface) works for trackpad and its gesture, and partical works for Sonoma for the touch screen and stylus.
